"""Improvement state model for the Burr workflow.

All state is JSON-serializable for Burr persistence. We store
references (IDs) only — never complete documents, embeddings,
or large artifacts. AI-Ready remains the source of truth for
knowledge data.

State keys used by Burr actions:
  remediation_id          — unique ID for this improvement attempt
  assessment_id           — the assessment that triggered this workflow
  signal_ids              — list of signal IDs that need improvement
  affected_artifact_ids   — list of artifact IDs needing changes
  affected_artifact_uris — list of artifact URIs (for executor lookups)
  current_stage           — current workflow stage (RemediationStatus)
  root_cause_analysis     — list of RootCauseHypothesis dicts
  proposals               — list of RemediationProposal dicts
  selected_proposal_idx   — index into proposals list
  approval_status         — "pending", "approved", "rejected"
  approval_reason         — optional reason from approver
  execution_history       — list of execution step dicts
  verification_results    — VerificationResult dict
  attempt_number          — which attempt (1 = first, 2 = forked retry, ...)
  forked_from_app_id      — prior app_id if this is a forked retry
  forked_from_sequence_id — prior sequence_id if forked
  prior_failures          — list of prior failure summaries for learning
  llm_metadata            — dict of LLM call metadata (provider, model, tokens)
  assessment_summary      — compact reusable summary built in analyze_issue (Obj 2, 9)
  cumulative_tokens       — running total of prompt+completion tokens across all actions (Obj 9)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class RemediationStatus(str, Enum):
    """Lifecycle stages for a knowledge improvement workflow."""

    DETECTED = "detected"
    ANALYZING = "analyzing"
    ROOT_CAUSE_FOUND = "root_cause_found"
    PROPOSAL_GENERATED = "proposal_generated"
    WAITING_FOR_APPROVAL = "waiting_for_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTING = "executing"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED_ANALYSIS = "failed_analysis"
    FAILED_EXECUTION = "failed_execution"
    FAILED_VERIFICATION = "failed_verification"


class VerificationOutcome(str, Enum):
    """Outcome of verifying a Knowledge Problem after remediation.

    Verification operates at the Knowledge Problem level, not individual
    signal level, because multiple problems can produce the same signal
    and one problem can produce many different signals.
    """

    RESOLVED = "resolved"              # All signals for this problem are gone
    PARTIALLY_RESOLVED = "partially_resolved"  # Some signals gone, some remain
    UNCHANGED = "unchanged"            # Same signals remain
    REGRESSED = "regressed"            # More signals than before
    MISDIAGNOSED = "misdiagnosed"       # Root cause was wrong — signals don't match


# Terminal states — workflow stops here
TERMINAL_STATES = {
    RemediationStatus.COMPLETED,
    RemediationStatus.REJECTED,
    RemediationStatus.FAILED_ANALYSIS,
    RemediationStatus.FAILED_EXECUTION,
    RemediationStatus.FAILED_VERIFICATION,
}

# Failure states — trigger forking
FAILURE_STATES = {
    RemediationStatus.FAILED_ANALYSIS,
    RemediationStatus.FAILED_EXECUTION,
    RemediationStatus.FAILED_VERIFICATION,
}


@dataclass
class RootCauseHypothesis:
    """A hypothesis about why a knowledge quality issue exists.

    Generated by the LLM inside AnalyzeIssueAction.
    """

    hypothesis: str
    evidence: list[str] = field(default_factory=list)
    confidence: float = 0.0  # 0.0 to 1.0
    affected_artifact_uris: list[str] = field(default_factory=list)
    category: str = ""  # e.g. "missing_metadata", "poor_structure", "duplicate_content"

    def to_dict(self) -> dict[str, Any]:
        return {
            "hypothesis": self.hypothesis,
            "evidence": self.evidence,
            "confidence": self.confidence,
            "affected_artifact_uris": self.affected_artifact_uris,
            "category": self.category,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RootCauseHypothesis:
        return cls(
            hypothesis=d.get("hypothesis", ""),
            evidence=d.get("evidence", []),
            confidence=d.get("confidence", 0.0),
            affected_artifact_uris=d.get("affected_artifact_uris", []),
            category=d.get("category", ""),
        )


@dataclass
class KnowledgeProblem:
    """A knowledge quality problem identified during root cause analysis.

    A Knowledge Problem is the underlying issue that produces signals.
    Multiple signals can stem from the same problem, and the same signal
    type can be produced by different problems. Verification operates at
    the problem level, not the signal level.
    """

    problem_id: str  # stable ID derived from category + artifact URIs
    category: str  # e.g. "missing_context", "poor_structure", "broken_links"
    description: str  # human-readable description
    root_cause_idx: int  # which RootCauseHypothesis this problem maps to
    signal_ids: list[str] = field(default_factory=list)
    artifact_uris: list[str] = field(default_factory=list)
    evidence_summary: str = ""  # summary of supporting evidence

    def to_dict(self) -> dict[str, Any]:
        return {
            "problem_id": self.problem_id,
            "category": self.category,
            "description": self.description,
            "root_cause_idx": self.root_cause_idx,
            "signal_ids": self.signal_ids,
            "artifact_uris": self.artifact_uris,
            "evidence_summary": self.evidence_summary,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> KnowledgeProblem:
        return cls(
            problem_id=d.get("problem_id", ""),
            category=d.get("category", ""),
            description=d.get("description", ""),
            root_cause_idx=d.get("root_cause_idx", 0),
            signal_ids=d.get("signal_ids", []),
            artifact_uris=d.get("artifact_uris", []),
            evidence_summary=d.get("evidence_summary", ""),
        )


@dataclass
class ProblemVerification:
    """Verification result for a single Knowledge Problem.

    Verification operates at the problem level, not signal level.
    One problem can produce many signals; multiple problems can produce
    the same signal type.
    """

    problem_id: str
    outcome: str  # VerificationOutcome value
    before_signal_count: int = 0
    after_signal_count: int = 0
    resolved_signal_ids: list[str] = field(default_factory=list)
    remaining_signal_ids: list[str] = field(default_factory=list)
    new_signal_ids: list[str] = field(default_factory=list)
    explanation: str = ""  # why this outcome was determined

    def to_dict(self) -> dict[str, Any]:
        return {
            "problem_id": self.problem_id,
            "outcome": self.outcome,
            "before_signal_count": self.before_signal_count,
            "after_signal_count": self.after_signal_count,
            "resolved_signal_ids": self.resolved_signal_ids,
            "remaining_signal_ids": self.remaining_signal_ids,
            "new_signal_ids": self.new_signal_ids,
            "explanation": self.explanation,
        }


@dataclass
class DecisionTrace:
    """Explainability chain for a single remediation workflow.

    Preserves the reasoning behind each stage so a developer can
    inspect the full decision chain:

    Knowledge Problem → Evidence → Root Cause → Historical Context →
    LLM Proposal → Approval → Execution → Verification → Final Outcome
    """

    knowledge_problems: list[dict[str, Any]] = field(default_factory=list)
    supporting_evidence: list[dict[str, Any]] = field(default_factory=list)
    root_cause_reasoning: str = ""  # LLM's reasoning for root cause
    historical_context_used: str = ""  # what history was retrieved and passed
    proposal_reasoning: str = ""  # LLM's reasoning for the proposal
    approval_decision: str = ""  # who approved/rejected and why
    execution_summary: str = ""  # what was executed
    verification_reasoning: str = ""  # why verification succeeded/failed
    final_outcome: str = ""  # overall outcome explanation

    def to_dict(self) -> dict[str, Any]:
        return {
            "knowledge_problems": self.knowledge_problems,
            "supporting_evidence": self.supporting_evidence,
            "root_cause_reasoning": self.root_cause_reasoning,
            "historical_context_used": self.historical_context_used,
            "proposal_reasoning": self.proposal_reasoning,
            "approval_decision": self.approval_decision,
            "execution_summary": self.execution_summary,
            "verification_reasoning": self.verification_reasoning,
            "final_outcome": self.final_outcome,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> DecisionTrace:
        return cls(
            knowledge_problems=d.get("knowledge_problems", []),
            supporting_evidence=d.get("supporting_evidence", []),
            root_cause_reasoning=d.get("root_cause_reasoning", ""),
            historical_context_used=d.get("historical_context_used", ""),
            proposal_reasoning=d.get("proposal_reasoning", ""),
            approval_decision=d.get("approval_decision", ""),
            execution_summary=d.get("execution_summary", ""),
            verification_reasoning=d.get("verification_reasoning", ""),
            final_outcome=d.get("final_outcome", ""),
        )


@dataclass
class RemediationProposal:
    """A proposed strategy for improving knowledge quality.

    Generated by the LLM inside GenerateProposalAction.

    Objective 4: Enhanced with affected_dimensions, confidence,
    assumptions, and rollback_considerations for richer proposals.
    """

    strategy: str  # e.g. "merge_documents", "add_metadata", "restructure"
    description: str
    expected_impact: str  # e.g. "+15 retrieval score"
    risks: list[str] = field(default_factory=list)
    affected_artifact_uris: list[str] = field(default_factory=list)
    modification_steps: list[dict[str, Any]] = field(default_factory=list)
    root_cause_idx: int = 0  # which hypothesis this addresses
    reasoning: str = ""  # Focus 7: LLM's reasoning for choosing this strategy
    # Objective 4: Enhanced proposal fields
    affected_dimensions: list[str] = field(default_factory=list)  # e.g. ["completeness", "accuracy"]
    confidence: float = 0.0  # 0.0 to 1.0 — LLM's confidence this strategy will work
    assumptions: list[str] = field(default_factory=list)  # assumptions the strategy depends on
    rollback_considerations: str = ""  # how to undo if it makes things worse

    def to_dict(self) -> dict[str, Any]:
        return {
            "strategy": self.strategy,
            "description": self.description,
            "expected_impact": self.expected_impact,
            "risks": self.risks,
            "affected_artifact_uris": self.affected_artifact_uris,
            "modification_steps": self.modification_steps,
            "root_cause_idx": self.root_cause_idx,
            "reasoning": self.reasoning,
            "affected_dimensions": self.affected_dimensions,
            "confidence": self.confidence,
            "assumptions": self.assumptions,
            "rollback_considerations": self.rollback_considerations,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RemediationProposal:
        return cls(
            strategy=d.get("strategy", ""),
            description=d.get("description", ""),
            expected_impact=d.get("expected_impact", ""),
            risks=d.get("risks", []),
            affected_artifact_uris=d.get("affected_artifact_uris", []),
            modification_steps=d.get("modification_steps", []),
            root_cause_idx=d.get("root_cause_idx", 0),
            reasoning=d.get("reasoning", ""),
            affected_dimensions=d.get("affected_dimensions", []),
            confidence=d.get("confidence", 0.0),
            assumptions=d.get("assumptions", []),
            rollback_considerations=d.get("rollback_considerations", ""),
        )


@dataclass
class VerificationResult:
    """Result of verifying whether an improvement worked.

    Computed by VerifyRemediationAction using AI-Ready's assessment pipeline.
    Verification operates at the Knowledge Problem level, not individual
    signal level, because multiple problems can produce the same signal
    and one problem can produce many different signals.
    """

    success: bool
    before_score: int = 0
    after_score: int = 0
    score_difference: int = 0
    resolved_signal_ids: list[str] = field(default_factory=list)
    new_signal_ids: list[str] = field(default_factory=list)
    remaining_signal_ids: list[str] = field(default_factory=list)
    dimension_deltas: dict[str, int] = field(default_factory=dict)
    summary: str = ""
    # Problem-level verification
    problem_verifications: list[dict[str, Any]] = field(default_factory=list)
    overall_outcome: str = ""  # VerificationOutcome value for the whole workflow
    failure_explanation: str = ""  # detailed explanation of why remediation failed

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "before_score": self.before_score,
            "after_score": self.after_score,
            "score_difference": self.score_difference,
            "resolved_signal_ids": self.resolved_signal_ids,
            "new_signal_ids": self.new_signal_ids,
            "remaining_signal_ids": self.remaining_signal_ids,
            "dimension_deltas": self.dimension_deltas,
            "summary": self.summary,
            "problem_verifications": self.problem_verifications,
            "overall_outcome": self.overall_outcome,
            "failure_explanation": self.failure_explanation,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> VerificationResult:
        return cls(
            success=d.get("success", False),
            before_score=d.get("before_score", 0),
            after_score=d.get("after_score", 0),
            score_difference=d.get("score_difference", 0),
            resolved_signal_ids=d.get("resolved_signal_ids", []),
            new_signal_ids=d.get("new_signal_ids", []),
            remaining_signal_ids=d.get("remaining_signal_ids", []),
            dimension_deltas=d.get("dimension_deltas", {}),
            summary=d.get("summary", ""),
            problem_verifications=d.get("problem_verifications", []),
            overall_outcome=d.get("overall_outcome", ""),
            failure_explanation=d.get("failure_explanation", ""),
        )


@dataclass
class RemediationOutcome:
    """Final outcome of an improvement workflow, stored in history.

    Used for institutional memory — future workflows query prior
    outcomes to inform strategy selection.
    """

    issue_type: str  # e.g. "duplicate_information", "broken_links"
    strategy: str  # e.g. "merge_documents", "add_redirects"
    result: str  # "success" or "failure"
    score_change: int = 0
    root_cause: str = ""
    artifact_uris: list[str] = field(default_factory=list)
    failure_reason: str = ""
    attempt_number: int = 1
    verification_outcome: str = ""  # VerificationOutcome value
    strategy_description: str = ""  # what the strategy actually did
    proposal_reasoning: str = ""  # LLM's reasoning for choosing this strategy

    def to_dict(self) -> dict[str, Any]:
        return {
            "issue_type": self.issue_type,
            "strategy": self.strategy,
            "result": self.result,
            "score_change": self.score_change,
            "root_cause": self.root_cause,
            "artifact_uris": self.artifact_uris,
            "failure_reason": self.failure_reason,
            "attempt_number": self.attempt_number,
            "verification_outcome": self.verification_outcome,
            "strategy_description": self.strategy_description,
            "proposal_reasoning": self.proposal_reasoning,
        }


def initial_state(
    remediation_id: str,
    assessment_id: str,
    signal_ids: list[str],
    affected_artifact_ids: list[str],
    affected_artifact_uris: list[str],
    prior_failures: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Create the initial Burr state dict for a new improvement workflow.

    Args:
        remediation_id: Unique ID for this improvement attempt.
        assessment_id: The assessment that triggered this workflow.
        signal_ids: Signal IDs that need improvement.
        affected_artifact_ids: Artifact IDs needing changes.
        affected_artifact_uris: Artifact URIs (for executor lookups).
        prior_failures: Optional list of prior failure summaries for learning.

    Returns:
        A dict suitable for ApplicationBuilder.with_state().
    """
    return {
        "remediation_id": remediation_id,
        "assessment_id": assessment_id,
        "signal_ids": signal_ids,
        "affected_artifact_ids": affected_artifact_ids,
        "affected_artifact_uris": affected_artifact_uris,
        "current_stage": RemediationStatus.DETECTED.value,
        "root_cause_analysis": [],
        "knowledge_problems": [],  # Focus 1: Knowledge Problem identification
        "proposals": [],
        "selected_proposal_idx": 0,
        "approval_status": "pending",
        "approval_reason": "",
        "execution_history": [],
        "verification_results": {},
        "attempt_number": 1,
        "forked_from_app_id": "",
        "forked_from_sequence_id": -1,
        "prior_failures": prior_failures or [],
        "prior_diagnosis": {},  # Focus 3: prior diagnosis from failed attempt
        "prior_strategy": {},  # Focus 3: prior strategy that failed
        "prior_verification": {},  # Focus 3: prior verification outcome
        "prior_execution": [],  # Focus 3: prior execution history
        "decision_trace": {},  # Focus 7: explainability chain
        "llm_metadata": {},
        "assessment_summary": "",  # Obj 2, 9: reusable compact summary persisted in state
        "cumulative_tokens": 0,  # Obj 9: running total of tokens across all LLM actions
    }
